<?php

declare(strict_types=1);

namespace GetWith\CoffeeMachine\Tests\Unit\Console;

use PHPUnit\Framework\TestCase;

/**
 * @internal
 * @coversNothing
 */
class MakeDrinkCommandTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testAssertTrue(): void
    {
        $this->assertTrue(true);
    }
}
