#!/bin/bash

docker run -it --rm                         \
    --name my-running-script                \
    --network coffee-machine_net            \
    -v "$PWD":/usr/src                      \
    -w /usr/src                             \
    coffee-machine.php-cli                  \
    tools/php-cs-fixer/vendor/bin/php-cs-fixer $@
